// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using facturi_backend.Data;

#nullable disable

namespace facturi_backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231122182848_InitializareDB")]
    partial class InitializareDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("facturi_backend.Models.DetaliiFactura", b =>
                {
                    b.Property<int>("IdDetaliiFactura")
                        .HasColumnType("int");

                    b.Property<int>("IdLocatie")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantitate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<string>("NumeProdus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PretUnitar")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Valoare")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdDetaliiFactura", "IdLocatie");

                    b.HasIndex("IdFactura", "IdLocatie")
                        .IsUnique();

                    b.ToTable("DetaliiFacturi");
                });

            modelBuilder.Entity("facturi_backend.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<int>("IdLocatie")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFacturare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<string>("NumarFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeClient")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFactura", "IdLocatie");

                    b.ToTable("Facturi");
                });

            modelBuilder.Entity("facturi_backend.Models.DetaliiFactura", b =>
                {
                    b.HasOne("facturi_backend.Models.Factura", "Factura")
                        .WithOne("DetaliiFactura")
                        .HasForeignKey("facturi_backend.Models.DetaliiFactura", "IdFactura", "IdLocatie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("facturi_backend.Models.Factura", b =>
                {
                    b.Navigation("DetaliiFactura");
                });
#pragma warning restore 612, 618
        }
    }
}
